const States = [
  { value: "alabama", name: "Alabama" },
  { value: "alaska", name: "Alaska" },
  { value: "arizona", name: "Arizona" },
  { value: "arkansas", name: "Arkansas" },
  { value: "california", name: "California" },
  { value: "colorado", name: "Colorado" },
  { value: "connecticut", name: "Connecticut" },
  { value: "delaware", name: "Delaware" },
  { value: "washington_dc", name: "Washington DC" },
  { value: "florida", name: "Florida" },
  { value: "georgia", name: "Georgia" },
  { value: "hawaii", name: "Hawaii" },
  { value: "idaho", name: "Idaho" },
  { value: "illinois", name: "Illinois" },
  { value: "indiana", name: "Indiana" },
  { value: "iowa", name: "Iowa" },
  { value: "kansas", name: "Kansas" },
  { value: "kentucky", name: "Kentucky" },
  { value: "louisiana", name: "Louisiana" },
  { value: "maine", name: "Maine" },
  { value: "maryland", name: "Maryland" },
  { value: "massachusetts", name: "Massachusetts" },
  { value: "michigan", name: "Michigan" },
  { value: "minnesota", name: "Minnesota" },
  { value: "mississippi", name: "Mississippi" },
  { value: "missouri", name: "Missouri" },
  { value: "montana", name: "Montana" },
  { value: "nebraska", name: "Nebraska" },
  { value: "nevada", name: "Nevada" },
  { value: "new_hampshire", name: "New Hampshire" },
  { value: "new_jersey", name: "New Jersey" },
  { value: "new_mexico", name: "New Mexico" },
  { value: "new_york", name: "New York" },
  { value: "north_carolina", name: "North Carolina" },
  { value: "north_dakota", name: "North Dakota" },
  { value: "ohio", name: "Ohio" },
  { value: "oklahoma", name: "Oklahoma" },
  { value: "oregon", name: "Oregon" },
  { value: "pennsylvania", name: "Pennsylvania" },
  { value: "rhode_island", name: "Rhode Island" },
  { value: "south_carolina", name: "South Carolina" },
  { value: "south_dakota", name: "South Dakota" },
  { value: "tennessee", name: "Tennessee" },
  { value: "texas", name: "Texas" },
  { value: "utah", name: "Utah" },
  { value: "vermont", name: "Vermont" },
  { value: "virginia", name: "Virginia" },
  { value: "washington", name: "Washington" },
  { value: "west_virginia", name: "West Virginia" },
  { value: "wisconsin", name: "Wisconsin" },
  { value: "wyoming", name: "Wyoming" },
];

export default States;
